name: Github Actions Demo
on: 
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps: 
      - run: echo "the job was automatically triggered by a ${{github.event_name}} event."
      - run: echo "this job is now running on a ${{runner.os}} server on github."
      - run: echo "The name of your branch is ${{github.ref}} and the repo is ${{github.repository}}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "the ${{github.repository}} repository has been cloned to the runner."
      - run: echo "the workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{github.workspace}}
      - run: echo "this job's status is ${{job.status}}"
  
  Test-Go-TestServer:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - name: Setup Go
          uses: actions/setup-go@v2
          with: 
            go-version: 1.16

        - name: Test
          run: go test -v ./...
      
